### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by AntelopShield** [nebulous42069/diggz#1]
Hi all,

I recently updated my shield which is running Xenon 3.4. I wanted to do the same for my PC which is running the 1.9 version. I tried to access the build wizard and received an error. I thought maybe it's because I have Kodi 20.1 so I uninstalled it and installed 20.2 but still the same error. I uninstalled Kodi from windows and reinstalled it with the same error. I tried to remove Kodi and the appdata, same error. I've installed other builds which work fine but it's just this particular one, which I like, and would prefer to have. I'm not sure why as it's installed on my shield fine. I essentially am asking what else do I need to get rid of to neutralize this error because I don't know what else there is. Please help. Here is my log after a fresh install of both Kodi and the build after the error. Thanks in advance!

https://paste.kodi.tv/yexofuruhe.kodi

I also got some feedback that there's an issue with an expired SSL certificate but I don't know a process to fix this.

**Comment by nebulous42069** [comment]
> Hi all,
> 
> I recently updated my shield which is running Xenon 3.4. I wanted to do the same for my PC which is running the 1.9 version. I tried to access the build wizard and received an error. I thought maybe it's because I have Kodi 20.1 so I uninstalled it and installed 20.2 but still the same error. I uninstalled Kodi from windows and reinstalled it with the same error. I tried to remove Kodi and the appdata, same error. I've installed other builds which work fine but it's just this particular one, which I like, and would prefer to have. I'm not sure why as it's installed on my shield fine. I essentially am asking what else do I need to get rid of to neutralize this error because I don't know what else there is. Please help. Here is my log after a fresh install of both Kodi and the build after the error. Thanks in advance!
> 
> https://paste.kodi.tv/yexofuruhe.kodi
> 
> I also got some feedback that there's an issue with an expired SSL certificate but I don't know a process to fix this.

https://diggz1.me/forum/index.php
